dist: xenial
language: python
python:
- '3.7'
deploy:
  provider: heroku
  api_key:
    secure: "y0bEOh9e0ifyTi+LKhedCK+9qmkvrX+dUZcwaPg+pj6KtXv9x0kjv2ZN7qot1QnHTMdd1ao1vEVLUYRncN5LnnAkBNpqZxv0f23ucQagQtJM5Z32IHJMIAreF8TqDtU/yV5u8u2nDwAGE9NmUDSa7EA6u8XjpwluZQ+vjj/padlcUVRnIWvLYLcMYAwHfG09oy+yj0wtt5x1+HDzSdBcCBeJ0HLKnH+MEhJwVS4naqKo1Lxhw80ebbCp5IQvY04zimbO+GVwjq7VD7inCixBMJyeCv2VnIzcpIfahhJYnrikV7byfBBnrknVSJBPvQJ8R97wa5PXRAsoZeazSoQgqNkG8tGPVUFYVH/5VSwp5GER4XZsgYQ5a6JkBqltL4Xxbh+DAI90t8Hcg3x28P7KBpQBSN8TS4H4/T4+lCQHPgTmUJoMTq827j/38mSCHso2ahwL3NzTBKRwn9VSXmm37x4mA7SrsHObX28PhZ1LGqodClzHoQ+seu8sDrliPwfhE0M1eh0PuVIytqIDiwRM4B2AXip0jv9bEsPablynn9/bjuWopcHiCUXv8Ea57iZB6FZ+oyuYPZf+vCQV7DV5SmRDfnjM1YBI6F1Y76i1rUccyD9P5ULmOO89kgPY0FfaMm46yqTL3axnEzfNSXzGhBkg6sR7pSZBQpjrj0T+mpA="
  app: churchillbot
  true: master
script: true
