dist: xenial
language: python
python:
- '3.7'
deploy:
  provider: heroku
  api_key:
    secure: "KJ3BRyXVnNFX4+MfCx0hBqSx0ctj5BoszXv4r5PfozzUnQA8CmyZ1+UT7NQXFcsE9WkmOP4/R+8qGqgyUoQgW0mD+GnUiVzEblivk9UMvWkL89lLQJuJO5LHArpEXIHweVJ5AN8iqpl5RzVAYq6KQ4700+J2BIdtwqh7+RZ3rX0ReQkkUS2b74rjorFrA9N0n+baFNzqbnIJxrvqM7p5qTJuPnAomdXIiEifJ0+Z+qUDYM9zcwgZS5g5AMYAeM20AR9yMv36SBXNFUCELI9qGWCoJGT4qVQtrSwbN+ZvqsH0BfUsJ3CPIGH8iDhf6KjURKJzsqEbcITXAXz0a6j5mDAl5FQvMSadIfO1jo+qTXLfGMKZFLPWCqKB+GxLKeG2zUaxZQPlN6nQFqG/pmcK1DuPZXxa30lb6f/klZLDtWA0r+jzQkLI7vsMyHjOreawc8Bp+KjT7M3G8VQ/QLSGmVBRiLnVB6WtpbEgRq61orBiIibgUWPV1qwhyG68wWVbcsdG1AjHrNkVQvL76X8GpMDxNWWQOrezjI3K7bWqmH2QhGMfXD4Ipb6+vpbc0KC4gogD3rh6871sWdhqK9T1KckHJEJoiBSX/E/OBwjGT0kuolK7IiSfuiI1ZKKWu8Zk7tRyP1eO5UkywabId9tXgxPAS/52RTbsx13uNEQt8Ys="
  app: churchillbot
  true: master
